robot:
  max_dist_tran: 5 # mm, maximum distance between set point and current pose.
  max_dist_rot: 0.05 # rad, maximum distance between set point and current pose.
  safety_mode: 1 # 0: none 1: truncate 2: stop
  operation_mode: 0 # 0: cartesian 1: joint
  safe_zone:
    xmin: -500
    xmax: 500
    ymin: 100
    ymax: 500
    zmin: 0
    zmax: 500

ftsensor:
  offset:
    fx: 0.504737
    fy: 2.39281
    fz: -1.95517
    tx: 0.240496
    ty: -0.106527
    tz: 0.00243297
  gravity:
    x: 0.0282715
    y: 0.00356048
    z: -2.31619
  COM:
    x: 3.0191e-05
    y: -0.000634964
    z: -0.0757638
  safety:
    fx: 25 # maximum: 20
    fy: 25 # maximum: 20
    fz: 45 # maximum: 60
    tx: 1.2 # maximum: 1
    ty: 1.2 # maximum: 1
    tz: 1.2 # maximum: 1
  transform_sensor_to_tool:
    x: 0 # meter
    y: 0
    z: 0.0654
    qw: 0.9808
    qx: 0
    qy: 0
    qz: 0.1951

##
## Device specific parameters
##
# ati netft
netft:
  ip_address: "192.168.1.1"
  sensor_name: "netft"
  frame_id: "end_effector"
  publish_rate: 1000
  print_flag: false
  file_path: "/usr0/home/yifanh/Git/catkin_ws/src/force_control/test/data/netft_data.txt"

# ABB EGM
egm:
  portnum: 6510
  print_flag: false
  file_path: "/usr0/home/yifanh/Git/catkin_ws/src/force_control/test/data/egm_data.txt"
