main_loop_rate: 500
main_duration: 10 # sec
stiffness:
  x: 0.1 # N/mm
  y: 0.1
  z: 0.1
comp1:
  k: 0.0008
  zero: 0
  pole: 0.98
comp2:
  k: 1.0
  zero: 0.0
  pole: 1.0
  limit: 100.0 # magnitude limit of output

forcecontrol_print_flag: true
forcecontrol_file_path: "/home/simplehands/catkin_ws/src/forcecontrol/data/forcecontrol_data.txt"
