# main function for testing
main_loop_rate: 500
main_duration: 10 # sec
main_setpose:
  x: -20
  y: 300
  z: 435
  q1: 0
  q2: 0
  q3: 1
  q4: 0
# controller
force_fb_selection: # 1 (keep force feedback) or 0 (block force feedback)
  x: 1 
  y: 1
  z: 1

# Force control parameters
# For each axis
#   k: stiffness
#   m: mass (kg)
#   alpha: viscous friction
FC_para_X:
  k: 0
  m: 1
  alpha: 100
FC_para_Y:
  k: 0
  m: 1
  alpha: 100
FC_para_Z:
  k: 0
  m: 5
  alpha: 500
FC_limit: 100.0 # (mm) magnitude limit of output  THIS WILL CREATE A BOUNDING BOX


forcecontrol_print_flag: true
forcecontrol_file_path: "/home/yifanh/Git/catkin_ws/src/forcecontrol/data/forcecontrol_data.txt"
