main_loop_rate: 500
main_duration: 20 # sec
stiffness:
  x: 0.05 # N/mm
  y: 0.05
  z: 0.05
comp1:
  k: 0.0008 # change to 0.004 to feel excited
  zero: 0.975
  pole: 0.98
comp2:
  k: 1.0
  zero: 0.0
  pole: 1.0
  limit: 100.0 # magnitude limit of output

forcecontrol_print_flag: true
forcecontrol_file_path: "/home/simplehands/catkin_ws/src/forcecontrol/data/forcecontrol_data.txt"
