# main function for testing
# TODO(yifan) move these to launch file
main_loop_rate: 500
main_duration: 15 # sec
main_setpose:
  x: 10
  y: 300
  z: 435
  q1: 0
  q2: 0
  q3: 1
  q4: 0
main_setforce: # possitive value: move in that direction
  f1: 0
  f2: 0
  f3: -2
  f4: 0
  f5: 0
  f6: 0

# controller
Transform: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
force_controlled_dimensions: 3

# Admittance control parameters
# For each axis
#   k: stiffness
#   m: mass (kg)
#   alpha: viscous friction
# TODO(yifan) we need to be able to set these online
AC_para_X: # first axis (if the axes are rotated)
  k: 0
  m: 1
  alpha: 100
AC_para_Y: # second axis (if the axes are rotated)
  k: 0
  m: 1
  alpha: 100
AC_para_Z: # third axis (if the axes are rotated)
  k: 0
  m: 3
  alpha: 300
AC_limit: 300.0 # (mm) magnitude limit of output  THIS WILL CREATE A BOUNDING BOX

# Force control PID Gains
FC_gains:
  IGain: 0.02 # 0.005
  PGain: 0.0 #0.4
  DGain: 0.00 #0.02
FC_I_Limit: 50 # Newton

forcecontrol_print_flag: true
forcecontrol_file_path: "/home/yifanh/Git/catkin_ws/src/forcecontrol/data/forcecontrol_data.txt"
