# main function for testing
# TODO(yifan) move these to launch file
main_loop_rate: 500 #500
main_duration: 4 # sec

# Admittance control parameters for the pseudo spring-mass-damper system
# The following parameters are the diagonal elements of the 6x6 matrices
#   Stiffness matrix as viewed in tool frame
Stiffness_matrix_diag_elements: [1, 1, 1, 1, 1, 1]
#   Inertia matrix as viewed in tool frame
Inertia_matrix_diag_elements: [1, 1, 1, 1, 1]
#   Damping coefficient matrix as viewed in tool frame
Damping_matrix_diag_elements: [100, 100, 100, 100, 100, 100]

# Force control PID Gains
FC_gains:
  IGain: 0.02 # 0.005
  PGain: 0.5 #0.4
  DGain: 0.00 #0.02
FC_I_Limit: 50 # Newton

forcecontrol_print_flag: true
forcecontrol_file_path: "/home/yifanh/Git/catkin_ws/src/forcecontrol/data/forcecontrol_data.txt"
