# ati netft
netft_ip_address: "192.168.1.1"
netft_sensor_name: "netft"
netft_frame_id: "end_effector"
netft_publish_rate: 1000
netft_print_flag: false
netft_file_path: "/home/yifanh/Git/catkin_ws/src/forcecontrol/data/netft_data.txt"

ati:
  offset: # will be added to the reading; in tool frame
    fx: -0.634416
    fy: 1.18294
    fz: -1.46919
    tx: 0.0128343
    ty: 0.0568577
    tz: -0.00325318
  gravity:
    x: 0.389051
    y: -0.0846534
    z: -9.96465
  COM:
    x: -0.0170055
    y: 0.0176335
    z: 0.0407426
  safety:
    fx: 20 # maximum: 20
    fy: 20 # maximum: 20
    fz: 45 # maximum: 60
    tx: 1 # maximum: 1
    ty: 1 # maximum: 1
    tz: 1 # maximum: 1

# ABB EGM
egm_portnum: 6510
egm_max_dist_tran: 5 # mm, maximum distance between set point and current pose. 
egm_max_dist_rot: 0.05 # rad, maximum distance between set point and current pose. 
                      # This two numbers plus 'K' and bandwidth in robostudio determine 
                      # how fast the robot will move.
egm_safety_mode: 1 # 0: none 1: truncate 2: stop
egm_operation_mode: 0 # 0: cartesian 1: joint
egm_print_flag: false
egm_file_path: "/home/yifanh/Git/catkin_ws/src/forcecontrol/data/egm_data.txt"
egm_safety_zone:
  xmin: -50
  xmax: 220
  ymin: 240
  ymax: 550
  zmin: 260
  zmax: 600
  
# force control