# ati netft
netft_ip_address: "192.168.1.1"
netft_sensor_name: "netft"
netft_frame_id: "end_effector"
netft_publish_rate: 1000
netft_print_flag: true
netft_file_path: "/home/yifanh/Git/catkin_ws/src/forcecontrol/data/netft_data.txt"

ati:
  offset: # will get subtracted
    fx: -5.13
    fy: 9.82
    fz: 9.74
    tx: 0.206
    ty: -0.147
    tz: 0.012
  safety:
    fx: 20 # maximum: 20
    fy: 20 # maximum: 20
    fz: 45 # maximum: 60
    tx: 1 # maximum: 1
    ty: 1 # maximum: 1
    tz: 1 # maximum: 1

# ABB EGM
egm_portnum: 6510
egm_max_dist_tran: 5 # mm, maximum distance between set point and current pose. 
egm_max_dist_rot: 0.05 # rad, maximum distance between set point and current pose. 
                      # This two numbers plus 'K' and bandwidth in robostudio determine 
                      # how fast the robot will move.
egm_safety_mode: 1 # 0: none 1: truncate 2: stop
egm_operation_mode: 0 # 0: cartesian 1: joint
egm_print_flag: true
egm_file_path: "/home/yifanh/Git/catkin_ws/src/forcecontrol/data/egm_data.txt"
egm_safety_zone:
  xmin: -100
  xmax: 400
  ymin: -600
  ymax: -200
  zmin: 22
  zmax: 500

# force control