# ati netft
netft_ip_address: "192.168.1.1"
netft_sensor_name: "netft"
netft_frame_id: "end_effector"
netft_publish_rate: 1000
netft_print_flag: true
netft_file_path: "/home/simplehands/catkin_ws/src/forcecontrol/data/netft_data.txt"

# ABB EGM
egm_portnum: 6510
egm_max_dist_tran: 5 # mm, maximum distance between set point and current pose. 
egm_max_dist_rot: 0.3 # rad, maximum distance between set point and current pose. 
                      # This two numbers plus 'K' and bandwidth in robostudio determine 
                      # how fast the robot will move.
egm_mode: 0 # 0: position control  1: velocity control  2: transparent control
egm_print_flag: true
egm_file_path: "/home/simplehands/catkin_ws/src/forcecontrol/data/egm_data.txt"
egm_safety:
  xmax: 286
  xmin: -30
  ymax: -200
  ymin: -400
  zmax: 468
  zmin: 335

# force control
ati:
  offset:
    fx: 1.84
    fy: -0.65
    fz: 2.4
    tx: -0.0042
    ty: -0.0050
    tz: -0.0145
